# Generated by Django 2.2 on 2021-03-06 12:06

from django.db import migrations, models
import super_auth.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('nationality', models.TextField(blank=True, null=True, verbose_name='Country')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d', verbose_name='User Image')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verification Code')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', super_auth.manager.UserManager()),
            ],
        ),
    ]
